# This workflow will install Python dependencies, run tests and lint with a single version of Python (3.7)

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    # Skip CI if [ci skip] in the commit message
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black isort numpy gym==0.18.0 scikit-learn fast_pytorch_kmeans
        
        # mujoco
        mkdir /root/.mujoco
        wget -q https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz -O mujoco.tar.gz
        tar -zxf mujoco.tar.gz -C "/root/.mujoco"
        rm mujoco.tar.gz
        pip install mujoco-py<2.2,>=2.1

        # openmpi and mpi4py
        sudo apt install -y -q openmpi-bin libopenmpi-dev
        pip install mpi4py
        
        # cpu version of pytorch
        pip install torch==1.11+cpu -f https://download.pytorch.org/whl/torch_stable.html
        
        # download and install shadowhand-gym
        # git clone https://github.com/szahlner/shadowhand-gym.git
        # pip install -e shadowhand-gym
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Check codestyle
      run: |
        make check-codestyle
        
    - name: Lint with flake8
      run: |
        make lint
        
    - name: Test with pytest
      run: |
        make pytest
